version: '3'

services:
  shiro:
    container_name: shiro
    image: ghcr.io/dante-dan/shiro:latest
    volumes:
      - ./.env:/app/.env
    restart: always
    environment:
      - NEXT_SHARP_PATH=/usr/local/lib/node_modules/sharp
    ports:
      - 2323:2323
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:2323"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 3
